name: Push Check

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.16

      - uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Check License Header
        uses: apache/skywalking-eyes/header@v0.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# ignore lint and test since rpcx and kitex is not compatibly.
#      - name: Lint
#        run: |
#          test -z "$(gofmt -s -l .)"
#          go vet -stdmethods=false $(go list ./...)

#      - name: Unit Test
#        run: go test -v -race -covermode=atomic -coverprofile=coverage.out ./...
